"""add movie uniqueness constraint

Revision ID: 93c24965e88f
Revises: 8efcd82bdd6e
Create Date: 2026-07-08 18:09:45.194480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c24965e88f'
down_revision: Union[str, Sequence[str], None] = '8efcd82bdd6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_movie_details', 'movies', ['title', 'director', 'release_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_movie_details', 'movies', type_='unique')
    # ### end Alembic commands ###
